name: PyInstaller

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller poc.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: |
        cd ./dist/poc
        ls
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          echo "Linux"
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          echo "MacOS"
        elif [[ "$OSTYPE" == "cygwin" ]]; then
          echo "Cygwin"
        elif [[ "$OSTYPE" == "msys" ]]; then
          echo "Msys"
        elif [[ "$OSTYPE" == "win32" ]]; then
          echo "Win32"
        elif [[ "$OSTYPE" == "freebsd"* ]]; then
          echo "freebsd"
        else
          echo "OSTYPE:" $OSTYPE
          echo ${{ matrix.os }}
        fi
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ matrix.os }}
        path: dist/*
