name: PyInstaller

on:
  push:
  workflow_dispatch:

env:
  URL_TEST: 'https://google.com.br'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:

    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Udpate url in __init__ file
      run: |
        echo "__url__ = \"${URL_TEST}\"" > ${{ github.workspace }}__init__.py
        cat ${{ github.workspace }}/__init__.py

    - run: pip install -r requirements.txt pyinstaller

    - run: pyinstaller poc.py --onefile --clean

    - name: Check files
      run: |
        cd ./dist
        ls

    - name: Extract Unix binary
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os }} != 'windows-latest'
      with:
        name: artifact-${{ matrix.os }}
        path: dist/poc

    - name: Extract Windows binary
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os }} == 'windows-latest'
      with:
        name: artifact-${{ matrix.os }}
        path: dist/poc.exe
