name: PyInstaller

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:

    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Udpate variables in __init__.py file (Unix)
      if: contains(fromJson('["ubuntu-latest", "macos-latest"]'), ${{ matrix.os }})
      run: |
        echo ${{ matrix.os }}
        echo "__version__ = \"${URL_VERSION}\"" > ${{ github.workspace }}/__init__.py
        echo "__url__ = \"${URL_TEST}\"" >> ${{ github.workspace }}/__init__.py
        cat ${{ github.workspace }}/__init__.py
      env:
        URL_TEST: 'https://google.com'
        URL_VERSION: '1.0.0'

    - name: Udpate variables in __init__.py file (Windows)
      if: ${{ matrix.os }} == 'windows-latest'
      run: |
        echo "__version__ = \"${URL_VERSION}\"" > ${{ github.workspace }}\__init__.py
        echo "__url__ = \"${URL_TEST}\"" >> ${{ github.workspace }}\__init__.py
        cat ${{ github.workspace }}\__init__.py
      env:
        URL_TEST: 'https://google.com'
        URL_VERSION: '1.0.0'
      shell: bash

    - run: pip install -r requirements.txt pyinstaller

    - name: Test script with new variables
      run: python3 poc.py

    - run: pyinstaller poc.py --onefile --clean

    - name: Check files
      run: |
        cd ./dist
        ls

    - name: Extract Unix binary
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os }} != 'windows-latest'
      with:
        name: artifact-${{ matrix.os }}
        path: dist/poc

    - name: Extract Windows binary
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os }} == 'windows-latest'
      with:
        name: artifact-${{ matrix.os }}
        path: dist/poc.exe
